// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxPG0Ca8K2jgSR-HQMjLG1OFABpf2hC7w',
    appId: '1:473653695845:web:8046b8ecd9b2bc9191bd8c',
    messagingSenderId: '473653695845',
    projectId: 'nutriailyze-app',
    authDomain: 'nutriailyze-app.firebaseapp.com',
    storageBucket: 'nutriailyze-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPEbUm7eHCnAgF8ES40F3hNFR8_uk_VaE',
    appId: '1:473653695845:android:2918d4d7cd81ac1591bd8c',
    messagingSenderId: '473653695845',
    projectId: 'nutriailyze-app',
    storageBucket: 'nutriailyze-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDARm_F0g6qI7B6g9aPVlVqcoUXvrN4LGg',
    appId: '1:473653695845:ios:94b3dc61508dc4ab91bd8c',
    messagingSenderId: '473653695845',
    projectId: 'nutriailyze-app',
    storageBucket: 'nutriailyze-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterNutriailyzeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDARm_F0g6qI7B6g9aPVlVqcoUXvrN4LGg',
    appId: '1:473653695845:ios:94b3dc61508dc4ab91bd8c',
    messagingSenderId: '473653695845',
    projectId: 'nutriailyze-app',
    storageBucket: 'nutriailyze-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterNutriailyzeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxPG0Ca8K2jgSR-HQMjLG1OFABpf2hC7w',
    appId: '1:473653695845:web:d3e562a6f5f5c2ee91bd8c',
    messagingSenderId: '473653695845',
    projectId: 'nutriailyze-app',
    authDomain: 'nutriailyze-app.firebaseapp.com',
    storageBucket: 'nutriailyze-app.firebasestorage.app',
  );
}
