import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:google_fonts/google_fonts.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:flutter_nutriailyze_app/generate_plan_output_screen.dart';

class LoadingPlanScreen extends StatefulWidget {
  final Map<String, dynamic>
  requestData; // Data from previous screen, the user's input and profile info

  // requestData is the data passed from the previous screen. It contains everything needed to generate the plan: Age, Weight, Height, Gender, Goal, and Text Input.
  const LoadingPlanScreen({super.key, required this.requestData});

  @override
  State<LoadingPlanScreen> createState() => _LoadingPlanScreenState();
}

class _LoadingPlanScreenState extends State<LoadingPlanScreen> {
  // As soon as this screen appears on the phone, it automatically triggers the _generatePlan() function. The user doesn't need to press anything.
  @override
  void initState() {
    super.initState();
    _generatePlan();
  }

  Future<void> _generatePlan() async {
    // Default to production API domain. Override with --dart-define=API_BASE_URL=... for local/dev builds.
    const String apiBaseUrl = String.fromEnvironment(
      'API_BASE_URL',
      defaultValue: 'https://api.nutriailyze.id.lv',
    );

    // Local examples:
    // Android emulator: --dart-define=API_BASE_URL=http://10.0.2.2:8000
    // iOS simulator: --dart-define=API_BASE_URL=http://127.0.0.1:8000
    // Physical device: --dart-define=API_BASE_URL=http://192.168.1.XX:8000
    final Uri url = Uri.parse(
      '$apiBaseUrl/generate-plan?use_ai=true', // This points to the configured backend endpoint and use_ai=true tells the backend to use the advanced AI logic (Gemini).
    );

    try {
      // 2. Make POST Request, sending the user's input and profile data as JSON in the body of the request.
      // await: The app pauses execution here (while showing the loading spinner) until the server replies. This might take 5-10 seconds
      final response = await http.post(
        url,
        headers: {"Content-Type": "application/json"},
        body: jsonEncode(
          widget.requestData,
        ), // Convert the requestData map to a JSON string before sending it in the body of the POST request.
      );

      if (!mounted) return;

      if (response.statusCode == 200) {
        // 3. Success! Parse data and navigate, unpack the JSON response
        final responseData = jsonDecode(response.body);

        // Backend may return partial_success with payload nested under `data`.
        // Normalize so result screen always receives a plan map with `meals` and `daily_targets`.
        Map<String, dynamic> normalizedPlanData;
        if (responseData is Map<String, dynamic> &&
            responseData['data'] is Map<String, dynamic>) {
          normalizedPlanData = Map<String, dynamic>.from(responseData['data']);
        } else if (responseData is Map<String, dynamic>) {
          normalizedPlanData = responseData;
        } else {
          throw const FormatException('Unexpected API response format.');
        }

        // 4. Move to the Result Screen
        Navigator.pushReplacement(
          context,
          MaterialPageRoute(
            builder: (context) => PlanResultScreen(
              planData:
                  normalizedPlanData, // The new plan data generated by the backend, which includes the meal plan and nutritional analysis.
              originalRequest: widget
                  .requestData, // Remember who asked for the plan, so we can show their input on the result screen if needed.
            ),
          ),
        );
      } else {
        _showError(
          "Server Error: ${response.statusCode}",
        ); // Error handling if the server responds with an error status code (not 200)
      }
    } catch (e) {
      // 5. Network or other error, such as the backend server not running or a connectivity issue. Show an error message to the user.
      if (mounted) _showError("Connection Failed: $e");
    }
  }

  //  Error helper function to show a red snackbar with the error message and then navigate back to the previous screen where the user can try again.
  void _showError(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text(message), backgroundColor: Colors.red),
    );
    Navigator.pop(context); // Go back to input screen
  }

  // This is the UI of the loading screen, which shows a logo, a spinner, and some text to let the user know that the plan is being generated.
  @override
  Widget build(BuildContext context) {
    // Scaffold is used because it provides a basic visual layout structure for the screen, including background color and a body where we can center our content.
    return Scaffold(
      backgroundColor: const Color(0xFF333333),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            SvgPicture.asset('assets/logos/LogoN.svg', height: 150),
            const SizedBox(height: 10),
            const CircularProgressIndicator(color: Color(0xFFE3DAC9)),
            const SizedBox(height: 20),
            Text(
              "Chef AI is cooking...",
              style: GoogleFonts.ptMono(
                color: const Color(0xFFF6F6F6),
                fontSize: 16,
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 10),
            Text(
              "Analyzing nutritional needs...",
              style: GoogleFonts.ptMono(
                color: const Color(0xFF8E8E8E),
                fontSize: 12,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
